version: '3.7'

services:
  pantheon:
    image: pegasyseng/pantheon:latest
    restart: unless-stopped
    ports:
      - 8545:8545 # http
      - 8546:8546 # Websocket
    volumes:
      - pantheon:/var/lib/pantheon
    command:
      - --miner-enabled
      - --miner-coinbase=fe3b557e8fb62b89f4916b721be55ceb828dbd73
      - --discovery-enabled=false
      - --min-gas-price=0
      - --rpc-http-cors-origins=all
      - --rpc-ws-enabled
      - --rpc-http-enabled
      - --network=dev
  explorer:
    image: alethio/ethereum-lite-explorer:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - APP_NODE_URL=http://127.0.0.1:8545

volumes:
  pantheon:
