version: '3.7'

services:
  explorer:
    image: alethio/ethereum-lite-explorer:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - APP_NODE_URL=http://127.0.0.1:8545

  pantheon:
    image: pegasyseng/pantheon:latest
    restart: unless-stopped
    ports:
      - 8545:8545 # http
      - 8546:8546 # Websocket
    command:
      - --miner-enabled
      - --miner-coinbase=fe3b557e8fb62b89f4916b721be55ceb828dbd73
      - --discovery-enabled=false
      - --min-gas-price=0
      - --rpc-http-cors-origins=all
      - --rpc-ws-enabled
      - --rpc-ws-api=ETH,NET,WEB3,DEBUG,ADMIN
      - --rpc-http-enabled
      - --rpc-http-api=ETH,NET,WEB3,DEBUG,ADMIN
      - --network=dev

  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545
      - 8546:8545
    command:
      - --gasPrice=0

  geth:
    image: ethereum/client-go:stable
    ports:
      - 8545:8545 # http
      - 8546:8546 # Websocket
    command:
      - --dev
      - --rpc
      - --rpcaddr
      - '0.0.0.0'
      - --ws
      - --wsaddr
      - '0.0.0.0'
      - --wsorigins
      - '*'
      - --gasprice
      - '0'
      - --targetgaslimit
      - '8000000'
